- name: "RandomForest"
  hyperparameters:
    n_estimators:
      type: "int"
      range: [50, 300]
    max_depth:
      type: "int"
      range: [2, 30]
  scalers: ["minmax", "standard", "robust"]
  dim_red: ["PCA", None]

- name: "CatBoost"
  hyperparameters:
    depth:
      type: "int"
      range: [2, 10]
    learning_rate:
      type: "float"
      range: [1e-3, 1.0]
    iterations:
      type: "int"
      range: [50, 300]
  scalers: ["minmax", "standard", "robust"]
  dim_red: ["PCA", None]
