classifiers:
- AdaBoostClassifier
- RandomForestClassifier
- DecisionTreeClassifier
- LogisticRegression
- GradientBoostingClassifier
- KNeighborsClassifier
base_model_name: AdaBoostClassifier
base_model_score: '0.8312638804764789'
