train_model:
  RandomForestClassifier:
    max_depth:
    - 5
    - 8
    max_features:
    - 5
    - 7
    n_estimators:
    - 1
    - 100
    - 200
  DecisionTreeClassifier:
    max_depth:
    - 1
    - 10
    - 20
    criterion:
    - gini
    - entropy
base_model_score: '0.7857142857142857'
