classifiers:
- AdaBoostClassifier
- RandomForestClassifier
- DecisionTreeClassifier
- LGBMClassifier
- LogisticRegression
- XGBClassifier
- CatBoostClassifier
- GradientBoostingClassifier
- KNeighborsClassifier
base_model_name: AdaBoostClassifier
base_model_score: '0.8312638804764789'
