classifiers:
  - RandomForestClassifier
  - DecisionTreeClassifier 
  - LGBMClassifier
  - XGBClassifier 
  - CatBoostClassifier 
  - LogisticRegression 
  - GradientBoosting 
  - KNeighborsClassifier 
base_model_name: DecisionTree
base_model_score: '0.8221387911553535'
