classifiers:
- AdaBoostClassifier
- RandomForestClassifier
- DecisionTreeClassifier
- LGBMClassifier
- LogisticRegression
- XGBClassifier
- CatBoostClassifier
- GradientBoostingClassifier
- KNeighborsClassifier

base_model_name: DecisionTreeClassifier
base_model_score: '0.8412638804764789'
