columns:
  - months_as_customer: int64
  - age: int64
  - policy_number: int64
  - policy_bind_date: object
  - policy_state: object
  - policy_csl: object
  - policy_deductable: int64
  - policy_annual_premium: float64
  - umbrella_limit: int64
  - insured_zip: int64
  - insured_sex: object
  - insured_education_level: object
  - insured_occupation: object
  - insured_hobbies: object
  - insured_relationship: object
  - capital_gains: int64
  - capital_loss: int64
  - incident_date: object
  - incident_type: object
  - collision_type: object
  - incident_severity: object
  - authorities_contacted: object
  - incident_state: object
  - incident_city: object
  - incident_location: object
  - incident_hour_of_the_day: int64
  - number_of_vehicles_involved: int64
  - property_damage: object
  - bodily_injuries: int64
  - witnesses: int64
  - police_report_available: object
  - total_claim_amount: int64
  - injury_claim: int64
  - property_claim: int64
  - vehicle_claim: int64
  - auto_make: object
  - auto_model: object
  - auto_year: int64
  - fraud_reported: object


numerical_columns:
  - months_as_customer 
  - age 
  - policy_number 
  - policy_annual_premium 
  - umbrella_limit 
  - insured_zip 
  - capital_gains 
  - capital_loss 
  - incident_hour_of_the_day 
  - total_claim_amount 
  - injury_claim 
  - property_claim 
  - vehicle_claim 
  - auto_year

  


categorical_columns:
  - policy_state 
  - policy_csl 
  - insured_sex 
  - insured_education_level 
  - insured_occupation 
  - insured_hobbies 
  - insured_relationship 
  - incident_type 
  - collision_type 
  - incident_severity 
  - authorities_contacted 
  - incident_state 
  - incident_city 
  - property_damage 
  - police_report_available 
  - auto_make 
  - fraud_reported 
  - policy_deductable 
  - number_of_vehicles_involved 
  - bodily_injuries 
  - witnesses

# features used for the pipeline
onehot_features:
  - policy_state 
  - collision_type
  - property_damage
  - police_report_available
  - insured_sex 
  - insured_education_level 
  - insured_relationship 
  - incident_type 
  - incident_severity 
  - authorities_contacted 
  - incident_state 
  - incident_city 
  - policy_deductable 
  - number_of_vehicles_involved 
  - bodily_injuries 
  - witnesses 
  - incident_period_of_day 

numerical_features:
  - months_as_customer 
  - age 
  - policy_annual_premium 
  - total_claim_amount 
  - injury_claim 
  - property_claim 
  - vehicle_claim 
  - vehicle_age

ordinal_features:
  - insured_occupation
  - insured_hobbies
  - auto_make

transform_features:
  - umbrella_limit
  - capital_gains
  - capital_loss

drop_columns:
  - policy_number
  - policy_bind_date
  - policy_csl
  - incident_hour_of_the_day
  - insured_zip
  - incident_date
  - incident_location
  - auto_model
  - auto_year

target_column: fraud_reported

incident_hour_time_bins:
  bins_hour: [-1, 5, 11, 17, 20, 24]
  names_period: ["early_morning", "morning", "afternoon", "evening", "night"]
