columns:
  - months_as_customer: int64
  - age: int64
  - policy_number: int64
  - policy_bind_date: object
  - policy_state: object
  - policy_csl: object
  - policy_deductable: int64
  - policy_annual_premium: float64
  - umbrella_limit: int64
  - insured_zip: int64
  - insured_sex: object
  - insured_education_level: object
  - insured_occupation: object
  - insured_hobbies: object
  - insured_relationship: object
  - capital-gains: int64
  - capital-loss: int64
  - incident_date: object
  - incident_type: object
  - collision_type: object
  - incident_severity: object
  - authorities_contacted: object
  - incident_state: object
  - incident_city: object
  - incident_location: object
  - incident_hour_of_the_day: int64
  - number_of_vehicles_involved: int64
  - property_damage: object
  - bodily_injuries: int64
  - witnesses: int64
  - police_report_available: object
  - total_claim_amount: int64
  - injury_claim: int64
  - property_claim: int64
  - vehicle_claim: int64
  - auto_make: object
  - auto_model: object
  - auto_year: int64
  - fraud_reported: object


numerical_columns:
  - months_as_customer
  - age 
  - policy_deductable
  - umbrella_limit
  - incident_hour_of_the_day 
  - number_of_vehicles_involved
  - bodily_injuries 
  - witnesses 
  - total_claim_amount


categorical_columns:
  - insured_sex
  - insured_education_level 
  - insured_occupation
  - incident_type 
  - collision_type
  - incident_severity
  - authorities_contacted 
  - property_damage 
  - police_report_available

onehot_columns:
  - insured_sex 
  - insured_education_level 
  - insured_occupation
  - incident_type 
  - collision_type 
  - incident_severity
  - authorities_contacted 
  - property_damage 
  - police_report_available


drop_columns:
  - policy_number
  - policy_bind_date
  - policy_state
  - policy_csl
  - policy_annual_premium
  - insured_zip
  - insured_hobbies
  - insured_relationship
  - capital-gains
  - capital-loss
  - incident_date
  - incident_state
  - incident_city
  - incident_location
  - injury_claim
  - property_claim
  - vehicle_claim
  - auto_make
  - auto_model
  - auto_year

binary_columns:
  - International


target_column: fraud_reported